# Generated by Django 5.1.7 on 2025-03-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-pub_date', 'title'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
    ]
