# Generated by Django 5.1.7 on 2025-03-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date_created', 'title'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='pub_date',
            new_name='date_created',
        ),
    ]
